stages:
- stage: build
  jobs:
  - job: buildjob
    pool: 
	  name: azure pipeline
      demand: maven
    steps:
    - task: maven@4 
      task-version: "4.*"
      inputs:
       name01: "Maven pom.xml"
       Maven-pom-file: "pom.xml"
       goals: package
       Publish-to-Azure-Pipelines: true
       Test-results-files: "**/surefire-reports/TEST-*.xml"
       Code-coverage-tool: none