trigger:
- none
stages:
- stage: Buildapplication
  jobs: 
  - job: Build
    pool:
     name: "Azure Pipelines"
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: package
        codeCoverageToolOption: none
   