trigger:
  - none
pool:
  name: "Azure Pipelines"
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #javaHomeOption: 'JDKVersion'
    #mavenVersionOption: 'Default'
    #mavenAuthenticateFeed: false
    #effectivePomSkip: false
    #sonarQubeRunAnalysis: false
    goals: package
    codeCoverageToolOption: None
    #allowBrokenSymlinks: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'