trigger:
 - none
stages:
- stage: Build
  jobs:
  - job: build
    pool:
     name: "Azure Pipelines"
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: package
        codeCoverageToolOption: none
    - task: CopyFiles@2
      displayName: "Copy Files to: $(build.artifactstagingdirectory)"
      inputs:
        SourceFolder: '$(system.DefaultWorkingDirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: raji"
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: raji
        publishLocation: "Container"
- stage: Deploy_dev
  jobs:
  - job: deploy
    pool:
     name: "Azure Pipelines"
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        itemPattern: '**/*.jar'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      displayName: "Deploy Azure App Service"
      inputs: 
       ConnectionType: AzureRM
       azureSubscription: "Free Trial (0842a7ee-3fe3-4df8-a868-313b0d4adf3a)"
       packageForLinux: "$(System.ArtifactsDirectory)/**/*.jar"
       appType: webAppLinux
       WebAppName: rajidevopsdev
- stage: deploy_uat
  jobs: 
  - job: Deploy
    pool:
     name: "Azure Pipelines"
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: specific
        itemPattern: '**/*.jar'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial (0842a7ee-3fe3-4df8-a868-313b0d4adf3a)'
        appType: 'webAppLinux'
        WebAppName: 'rajidevopsuat'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.jar'
   